title: Tierrating
description: Sync and organize your media ratings in customizable tier lists with seamless third-party provider integration.
theme: just-the-docs

url: https://docs.tierrating.de

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
